repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
      - id: ruff-format
      - id: ruff
        args: [ "--fix", "--select", "F401" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^.*.py$
        additional_dependencies: [ types-PyYAML, pydantic, types-requests ]
  - repo: local
    hooks:
      - id: custom-commit-msg-check
        name: Custom Commit Message Checker
        entry: scripts/check-commit-msg.sh
        language: script
        stages: [ commit-msg ]
