version: 1.0
table:
  name: "tap_store_sales_cleaned"
  description: "TM tap in-store sales"
  tags:
    "owner__tech": "Datahub (To Be Confirmed)"
    "data__supplier": "TAP"
    "data__domain": "finance"
    "pii__exists": "true"
    "pii__classification": "internal"
  primary_keys:
    - "invoice_id"
    - "unique_product_key"
  deduplication_keys:
    - "transaction_date"
  flatten_config:
    cols_to_exclude:
      - "_metadata"
  clustering_keys:
    - "transaction_date"
  columns:
    - name: "transaction_date"
      type: "date"
      transform: "to_date(Transaction_Date, 'yyyyMMdd')"
    - name: "store_number"
      source_col_name: "Store_Number"
      type: "integer"
    - name: "store_name"
      source_col_name: "Store_Name"
      type: "string"
    - name: "store_format"
      source_col_name: "Store_Format"
      type: "string"
    - name: "country_code"
      source_col_name: "Country_Code"
      type: "string"
    - name: "checkout_number"
      source_col_name: "Checkout_Number"
      type: "string"
    - name: "order_reference"
      source_col_name: "Order_Reference"
      type: "string"
    - name: "invoice_id"
      source_col_name: "Invoice_ID"
      type: "string"
      description: "Invoice identifier (transaction id)"
    - name: "customer_id"
      source_col_name: "Customer_ID"
      type: "string"
      create_hashed_col: true
      description: "Customer identifier"
    - name: "gtin"
      source_col_name: "GTIN"
      type: "long"
    - name: "unique_product_key"
      source_col_name: "Unique_Product_Key"
      type: "string"
    - name: "tpna"
      source_col_name: "TPNA"
      type: "integer"
    - name: "tpnb"
      source_col_name: "TPNB"
      type: "integer"
    - name: "tpnc"
      source_col_name: "TPNC"
      type: "integer"
    - name: "product_description"
      source_col_name: "Product_Description"
      type: "string"
    - name: "subclass_code"
      source_col_name: "Subclass_Code"
      type: "string"
    - name: "subclass_name"
      source_col_name: "Subclass_Name"
      type: "string"
    - name: "brand"
      source_col_name: "Brand"
      type: "string"
    - name: "quantity"
      source_col_name: "Quantity"
      type: "integer"
    - name: "uom"
      source_col_name: "UOM"
      type: "string"
    - name: "price_before_discounts_amount"
      source_col_name: "Price_Before_Discounts"
      type: "double"
      description: "Price before discounts in GBP"
    - name: "multi_saver_discount_amount"
      source_col_name: "Multi_Saver_Discount"
      type: "double"
      description: "Multi-saver discount amount in GBP"
    - name: "price_cut_discount_amount"
      source_col_name: "Price_Cut_Discount"
      type: "double"
      description: "Price cut discount amount in GBP"
    - name: "colleague_discount_amount"
      source_col_name: "Colleague_Discount"
      type: "double"
      description: "Colleague discount amount in GBP"
    - name: "coupon_discount_amount"
      source_col_name: "Coupon_Discount"
      type: "double"
      description: "Coupon discount amount in GBP"
    - name: "price_after_discounts_amount"
      source_col_name: "Price_After_Discounts"
      type: "double"
      description: "Price after discounts in GBP"
    - name: "refund_amount"
      source_col_name: "Refund_Amount"
      type: "double"
      description: "Refund amount in GBP"
    - name: "return_quantity"
      source_col_name: "Return_Quantity"
      type: "integer"
    - name: "return_reason"
      source_col_name: "Return_Reason"
      type: "string"
    - name: "net_sales_gl_amount"
      source_col_name: "Net_Sales_GL"
      type: "double"
      description: "Net sales GL amount in GBP"
    - name: "tax_band"
      source_col_name: "Tax_Band"
      type: "string"
    - name: "vat_amount"
      source_col_name: "VAT_Amount"
      type: "double"
      description: "VAT amount in GBP"
    - name: "clubcard_points_earned"
      source_col_name: "Clubcard_Points_Earned"
      type: "integer"
