version: 1.0
table:
  name: "tap_online_sales_cleaned"
  description: "TM tap direct online sales"
  tags:
    "owner__tech": "Datahub (To Be Confirmed)"
    "data__supplier": "TAP"
    "data__domain": "finance"
    "pii__exists": "true"
    "pii__classification": "internal"
  primary_keys:
    - "sale_identifier"
    - "base_product_number"
  deduplication_keys:
    - "order_date"
  flatten_config:
    cols_to_exclude:
      - "_metadata"
  clustering_keys:
    - "order_date"
  columns:
    - name: "sale_identifier"
      type: "string"
    - name: "base_product_number"
      type: "string"
    - name: "long_description"
      type: "string"
    - name: "product_sub_group_code"
      type: "string"
    - name: "dispatch_date"
      source_col_name: "despatch_date"
      type: "date"
    - name: "header_date"
      type: "date"
    - name: "sales_value"
      type: "double"
    - name: "discount_value"
      type: "double"
    - name: "cat_item_ref"
      type: "string"
    - name: "cat_bundle_ref"
      type: "string"
    - name: "order_date"
      type: "date"
    - name: "order_channel_type"
      type: "string"
    - name: "delivery_channel_type"
      type: "string"
    - name: "retail_outlet_number"
      type: "integer"
    - name: "credited_method"
      type: "string"
    - name: "clubcard_number"
      type: "string"
    - name: "transaction_type"
      type: "string"
    - name: "cust_order_number"
      type: "string"
    - name: "return_method"
      type: "string"
    - name: "return_reason_code"
      type: "string"
    - name: "scanned_sales_qty"
      type: "integer"
    - name: "cost_of_goods_sold"
      type: "double"
